### PR TITLE
Introducing Haml into chat-space directory

### PR DESCRIPTION
**Pull request by BayG**
- Installed Haml Gem.

- Converted .erb file to .haml file.

- Deleted application.html.erb file.

### CODE REVIEW

**Comment by motemotenten** [comment]
pullrequest の書き方なんですが、

# what
# why 
 というようなフォーマットに従った書き方にしましょう

**Comment by BayG** [comment]
了解です。pullrequest修正します。

**Comment by BayG** [comment]
## What

- Installed Haml Gem.

- Converted .erb file to .haml file.

- Deleted application.html.erb file.

## Why

- For using haml feature on Rails 5

- For simplifying the markup process.

- Became needless due to already converting erb to Haml.

**Comment by BayG** [comment]
改めて確認。Merge して宜しいですか。

**Comment by BayG** [comment]
Merge done. Deleted addHaml branch. 
Created 'ChatSpace-front-mounting' branch at local repository for next step.

**Pull request merged**
